#!/bin/sh
#
#  This script sets up Zypper for OpenSUSE
#

prefix=$1


#
#  Source our common functions
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
#  DNS is probably required to run "zypper update".
#
cp /etc/resolv.conf ${prefix}/etc


    
#
# Update zypper
#
if [ ! -d ${prefix}/proc ]; then
    mkdir -p ${prefix}/proc
fi
mount -o bind /proc ${prefix}/proc
chroot ${prefix} /usr/bin/zypper -n update
umount ${prefix}/proc

#
#  Log our finish
#
logMessage Script $0 finished




