#!/bin/sh
#
#  Install modules from the host system into the new image.
#
# Steve
# --
# http://www.steve.org.uk/


prefix=$1



#
#  Source our common functions
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
#  Copy the modules from the host to the new system - we should only
# really copy the *correct* modules, but we don't know what they are.
#
mkdir -p ${prefix}/lib/modules

# If we were not supplied a valid modules directory, just use the standard one
if [ -z "${modules}" -o ! -d "${modules}" ]; then
	modules=/lib/modules/*
fi
echo "Copying ${modules}"
cp -au ${modules} ${prefix}/lib/modules

# Suse seems to have a weird module dependency setup, it cant just use the normal dependency files
chroot ${prefix} /sbin/depmod -a `ls -1 ${prefix}/lib/modules`

#
#  Log our finish
#
logMessage Script $0 finished
