#!/bin/sh
#
#  This script ensures the new image has locales setup correctly.
#

prefix=$1


#
#  Source our common functions
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
#  Install the package
#
installPackage ${prefix} glibc-locale



#
# Log our finish
#
logMessage Script $0 finished.
