#!/bin/sh
#
#  This script disables resolvconf, since we do not want it tampered with.



prefix=$1


#
#  Source our common functions
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting

# Stop resolvconf service from starting
echo manual > ${prefix}/etc/init/resolvconf.override


# unlink it so we can put a new one in later
rm ${prefix}/etc/resolv.conf

# Put back whatever was picked up
cp ${prefix}/etc/resolvconf/resolv.conf.d/original ${prefix}/etc/resolv.conf

#
#  Log our finish
#
logMessage Script $0 finished
