#!/bin/sh
#
#  This script cleans the yum database on the new system.
#
# Steve
# --
# http://www.steve.org.uk/


prefix=$1

#
#  Source our common functions
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
# Clean up RPM files.
#
logMessage Cleaning .rpm* files.
find ${prefix}/ -name '*.rpmorig' -exec rm -f \{\} \;
find ${prefix}/ -name '*.rpmnew' -exec rm -f \{\} \;

#
#  Clean yum
#
logMessage Cleaning Yum Repository

if [ ! -d ${prefix}/proc ]; then
    mkdir -p ${prefix}/proc
fi
mount -o bind /proc ${prefix}/proc
chroot ${prefix} /usr/bin/yum  clean all
umount ${prefix}/proc

# Clean on each boot; work around an issue where yum would freeze the entire system and eventually print 'Task blocked for 120 seconds'
sed -i 's/exit 0//' ${prefix}/etc/rc.local
cat >> ${prefix}/etc/rc.local <<'EOT'
yum clean metadata
exit 0
EOT


#
#  Log our finish
#
logMessage Script $0 finished
