#!/bin/sh
#
# plymouth switches virtual terminals but doesnt exit cleanly, so its easier to just disable it for compatibility with xen VNC sessions

prefix=$1


#
#  Source our common functions
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


if [ -x ${prefix}/bin/plymouth ] ; then
	logMessage Disabling plymouth
	chmod -x ${prefix}/bin/plymouth
fi

# if plymouth comes back (eg apt-get upgrade), we wont have a visible terminal
# unless we run a getty on tty7
logMessage "Adding tty7 for Plymouth compatibility"

copy_tty_device=tty1
if [ ! -z "${serial_device}" ]; then
    copy_tty_device=`basename ${serial_device}`
fi

cp -a ${prefix}/etc/init/${copy_tty_device}.conf  ${prefix}/etc/init/tty7.conf
sed -i -e s/${copy_tty_device}/tty7/ ${prefix}/etc/init/tty7.conf
echo tty7 >> ${prefix}/etc/securetty

#
#  Log our finish
#
logMessage Script $0 finished
